---
title: "thesis_data_regression_1_final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(devtools)
library(readxl)
library(foreign)
library(plm)
library(lmtest)
library(janitor)
library(stargazer)
library(broom)
library(gt)
library(tidyverse)
```

```{r load currency data}

#currency in circulation 

ifs_cic <- read_xlsx("raw-data/international_financial_statistics_ updated.xlsx") %>%
  gather(year, value, -c(country)) %>%
  drop_na() %>%
  mutate(cic = value * 1000000) %>%
  select(-value) %>%
  mutate(year = as.numeric(year)) %>%
filter(year != "1997") %>%
filter(year != "1998") %>%
filter(year != "1999") 

#gdp

gdp_final <- read_csv("raw-data/gdp_weo_2.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(gdp = value)

#cash demand
 
cash_demand <- ifs_cic %>%
full_join(gdp_final, by = c("year", "country")) %>%
mutate(cd = cic/gdp) %>%
mutate(log_cd = log(cd)) %>%
mutate(log_cic = log(cic)) %>%
filter(log_cd != "-Inf") %>%
arrange(desc(cd))


```

```{r load explanatory variables data sets}

#interest rates

deposit_interest_rate <- read_csv("raw-data/interest_rates_wdi.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(deposit_interest_rate = value) 

treasury_bill_rate <- read_xlsx("raw-data/imf_treasury_bill_interest_rates.xlsx", skip = 5) %>%
select(-`Scale`, -`Base Year`) %>%
gather(Year, Value, -c(Country)) %>%
filter(Value != "...") %>%
rename(year = Year) %>%
rename(treasury_bill_rate = Value) %>%
mutate(treasury_bill_rate = as.numeric(treasury_bill_rate)) %>%
mutate(treasury_bill_rate = round(treasury_bill_rate, digits = 4)) %>%
rename(country = Country) %>%
mutate(year = as.numeric(year)) %>%
filter(year != "NA")  

#economic complexity index

eci <- read_csv("raw-data/eci_country_rankings.csv")  %>%
clean_names() %>%
select(-country_id) %>%
mutate(year = as.numeric(year))

eci_ea <- eci %>%
  mutate(euro_area = ifelse(country %in% c("Germany", "Spain", "France", "Italy", "Netherlands", "Austria", "Belgium", "Cyprus", "Estonia", "Finland", "Greece", "Ireland", "Lithuania", "Portugal", "Slovakia", "Slovenia"), 1, 0)) %>%
  filter(euro_area == 1) %>%
  group_by(year) %>%
  summarize(eci = mean(eci)) %>%
  mutate(country = "Euro Area") 

eci_final <- eci_ea %>%
  full_join(eci, by = c("country", "year", "eci"))

#uncertainty index

uncertainty_2 <- read_excel("raw-data/uncertainty.xlsx") %>%
mutate(year = str_sub(year, 1,4)) %>%
mutate(year = as.numeric(year)) %>%
pivot_longer(-year, names_to = "country_code", values_to = "uncertainty") %>%
group_by(country_code, year) %>%
summarize(uncertainty = round(mean(uncertainty, na.rm = TRUE), digits = 4)) %>%
mutate(uncertainty = as.numeric(uncertainty))

#%>%
#mutate(uncertainty = round(uncertainty, digits = 2)) %>%
#filter(uncertainty != 0.00)

#year = str_sub(year, 1,4),
#
#summarize(uncertainty = round(mean(uncertainty, na.rm = TRUE), digits = 2)) %>%
#quarter = str_sub(year, 6)

uncertainty_ea_2 <- uncertainty_2 %>%
  mutate(euro_area = ifelse(country_code %in% c("DEU", "ESP", "FRA", "ITA", "NLD", "IRL"), 1, 0)) %>%
  filter(euro_area == 1) %>%
  group_by(year) %>%
  summarize(uncertainty = mean(uncertainty)) %>%
  mutate(country_code = "EMU")

uncertainty_final_2 <- uncertainty_ea_2 %>%
  full_join(uncertainty_2, by = c("country_code", "year", "uncertainty"))

#tax to gdp

tax_gdp_final <- read_csv("raw-data/tax_gdp.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
rename(country = `Country Name`) %>%
mutate(year = as.numeric(year)) %>%
mutate(country = as.character(country)) %>%
rename(country_code = `Country Code`) %>%
drop_na() %>%
rename(tax_gdp = value) 


#economic freedom indicies 

economic_freedom <- read_csv("raw-data/data.csv") %>%
  clean_names() %>%
  rename(country = name) %>%
  rename(year = index_year) %>%
  mutate(overall_score = as.numeric(overall_score)) %>%
  mutate(business_freedom = as.numeric(business_freedom)) %>%
  mutate(monetary_freedom = as.numeric(monetary_freedom)) %>%
  mutate(financial_freedom = as.numeric(financial_freedom)) %>%
  mutate(investment_freedom = as.numeric(investment_freedom)) %>%
  mutate(trade_freedom = as.numeric(trade_freedom)) %>%
  mutate(government_integrity = as.numeric(government_integrity)) %>%
  mutate(judicial_effectiveness = as.numeric(judicial_effectiveness)) %>%
  mutate(tax_burden = as.numeric(tax_burden)) %>%
  mutate(government_spending = as.numeric(government_spending)) %>%
  mutate(property_rights = as.numeric(property_rights)) %>%
  mutate(fiscal_health = as.numeric(fiscal_health)) %>%
  mutate(labor_freedom = as.numeric(labor_freedom))

economic_freedom_ea <- economic_freedom %>%
  mutate(euro_area = ifelse(country %in% c("Germany", "Spain", "France", "Italy", "Netherlands", "Austria", "Belgium", "Cyprus", "Estonia", "Finland", "Greece", "Ireland", "Latvia", "Lithuania", "Luxembourg", "Malta", "Portugal", "Slovakia", "Slovenia"), 1, 0)) %>%
  filter(euro_area == 1) %>%
  group_by(year) %>%
  summarize(monetary_freedom = mean(monetary_freedom, na.rm = TRUE),
          business_freedom = mean(business_freedom, na.rm = TRUE),
          property_rights = mean(property_rights, na.rm = TRUE),
          investment_freedom = mean(investment_freedom, na.rm = TRUE),
          financial_freedom = mean(financial_freedom, na.rm = TRUE), 
          trade_freedom = mean(trade_freedom, na.rm = TRUE),
          government_integrity = mean(government_integrity, na.rm = TRUE),
          judicial_effectiveness = mean(judicial_effectiveness, na.rm = TRUE)) %>%
  mutate(country = "Euro Area") 

economic_freedom_final <- economic_freedom_ea %>%
  full_join(economic_freedom, by = c("country", "year", "monetary_freedom", "business_freedom", "property_rights", "investment_freedom", "financial_freedom", "trade_freedom", "government_integrity", "judicial_effectiveness")) %>%
  arrange(country, year)

#estimates of the shadow economy 

shadow_economy <- read_xlsx("raw-data/shadow_economy.xlsx") %>%
select(-`No.`, -`Av. over years`) %>%
gather(year, value, -c(`Country`)) %>%
rename(country = `Country`) %>%
rename(shadow_economy = value) %>%
mutate(shadow_economy = as.numeric(shadow_economy)) %>%
arrange(country, year) %>%
mutate(year = as.numeric(year)) 

shadow_economy_ea <- shadow_economy %>%
  mutate(euro_area = ifelse(country %in% c("Germany", "Spain", "France", "Italy", "Netherlands", "Austria", "Belgium", "Cyprus", "Estonia", "Finland", "Greece", "Ireland", "Latvia", "Lithuania", "Luxembourg", "Malta", "Portugal", "Slovakia", "Slovenia"), 1, 0)) %>%
  filter(euro_area == 1) %>%
  group_by(year) %>%
  summarize(shadow_economy = mean(shadow_economy)) %>%
   mutate(country = "Euro Area") 
  
shadow_economy_final <- shadow_economy_ea %>%
  full_join(shadow_economy, by = c("country", "year", "shadow_economy"))

#urbanization 

urbanization_final <- read_csv("raw-data/urbanization.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
mutate(value = round(value, digits = 3)) %>%
rename(urbanization = value) 

#urban population growth

urban_pop_growth_final <- read_csv("raw-data/urban_pop_growth.csv", skip = 4) %>%
  select(-`Indicator Name`, -`Indicator Code`)%>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(urban_pop_growth = value) 

#crime statistics 

crime <- read_csv("raw-data/intentional_homocide.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(crime = value) 

crime_ea <- crime %>%
  mutate(euro_area = ifelse(country %in% c("Germany", "Spain", "France", "Italy", "Netherlands", "Austria", "Belgium", "Cyprus", "Estonia", "Finland", "Greece", "Ireland", "Latvia", "Lithuania", "Luxembourg", "Malta", "Portugal", "Slovakia", "Slovenia"), 1, 0)) %>%
  filter(euro_area == 1) %>%
  group_by(year) %>%
  summarize(crime = mean(crime)) %>%
   mutate(country = "Euro Area") 
  
crime_final <- crime_ea %>%
  full_join(crime, by = c("country", "year", "crime"))


```

```{r full data set creation}

final_regression_1_data <- cash_demand %>%
  full_join(deposit_interest_rate, by = c("country", "country_code", "year")) %>%
  full_join(treasury_bill_rate, by = c("country", "year")) %>%
  full_join(tax_gdp_final, by = c("country", "country_code", "year")) %>%
  full_join(eci_final, by = c("country", "year")) %>%
  full_join(uncertainty_final_2, by = c("country_code", "year")) %>%
  full_join(economic_freedom_final, by = c("country", "year")) %>%
  full_join(shadow_economy_final, by = c("country", "year")) %>%
  full_join(urbanization_final, by = c("country", "country_code", "year")) %>%
  full_join(crime_final, by = c("country", "country_code", "year")) %>%
  full_join(urban_pop_growth_final, by = c("country", "country_code", "year")) %>%
  mutate(region = ifelse(country %in% c("Australia", "Brunei Darussalam", "Cambodia", "Fiji", "Hong Kong", "Indonesia", "Japan", "Korea, Rep.", "Macao", "Malaysia", "Mongolia", "Myanmar", "Thailand", "Papua New Guinea", "Philippines", "Samoa", "Singapore", "Solomon Islands", "Tonga", "Vanuatu", "New Zealand"), "East Asia and Pacific",
          ifelse(country %in% c("Albania", "Armenia", "Azerbaijan", "Belarus", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Czech Republic", "Denmark", "Euro Area", "Georgia", "Hungary", "Iceland", "Kazakhstan", "Kyrgyz Republic", "Moldova", "North Macedonia", "Norway", "Poland", "Romania", "Serbia", "Sweden", "Switzerland", "Tajikistan", "Turkey", "Ukraine", "United Kingdom"), "Europe and Central Asia", 
           ifelse(country %in% c("Antigua and Barbuda", "Argentina", "Bahamas", "Barbados", "Belize", "Bolivia", "Brazil", "Chile", "Colombia", "Costa Rica", "Dominica", "Dominican Republic", "Grenada", "Guatemala", "Guyana", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "St. Kitts and Nevis", "St. Lucia", "St. Vincent and the Grenadines", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela, RB"), "Latin America and The Caribbean",
            ifelse(country %in% c("Algeria", "Djibouti", "Egypt", "Iraq", "Israel", "Jordan", "Kuwait", "Morocco", "Oman", "Qatar", "Syrian Arab Republic", "Tunisia", "United Arab Emirates"), "Middle East and North Africa", 
             ifelse(country %in% c("Canada", "United States"), "North America",
              ifelse(country %in% c("Afghanistan", "Bangladesh", "Bhutan", "India", "Maldives", "Nepal", "Pakistan", "Sri Lanka"), "South Asia",
               ifelse(country %in% c("Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Republic", "Chad", "Comoros", "Congo DR", "Congo, Rep.", "Cote d'Ivoire", "Equatorial Guinea", "Eritrea", "Eswatini", "Gabon", "Ghana", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Madagascar", "Mali", "Mauritania", "Mauritius", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "South Africa", "South Sudan", "Sudan", "Tanzania", "Togo", "Uganda", "Zambia", "Zimbabwe"), "Sub-Saharan Africa", "NA")))))))) %>%
   mutate(development = ifelse(country %in% c("Afghanistan", "Benin", "Burkina Faso", "Burundi", "Central African Republic", "Chad", "Congo DR", "Eritrea", "Guinea-Bissau", "Haiti", "Liberia", "Madagascar", "Mali", "Mozambique", "Nepal", "Niger", "Rwanda", "Sierra Leone", "South Sudan", "Syrian Arab Republic", "Tajikistan", "Tanzania", "Togo", "Uganda"), "Low-Income Economies",
                        ifelse(country %in% c("Angola", "Bangladesh", "Bhutan", "Bolivia", "Cabo Verde", "Cambodia", "Cameroon", "Comoros", "Congo, Rep.", "Cote d'Ivoire", "Djibouti", "Egypt", "Eswatini", "Ghana", "Honduras", "India", "Indonesia", "Kenya", "Kyrgyz Republic", "Lesotho", "Mauritania", "Moldova", "Mongolia", "Morocco", "Myanmar", "Nicaragua", "Nigeria", "Pakistan", "Papua New Guinea", "Philippines", "Sao Tome and Principe", "Senegal", "Solomon Islands", "Sudan", "Tunisia", "Ukraine", "Vanuatu", "Zambia", "Zimbabwe"), "Lower-Middle-Income Economies", 
                        ifelse(country %in% c("Albania", "Algeria", "Argentina", "Armenia", "Azerbaijan", "Belarus", "Belize", "Bosnia and Herzegovina", "Botswana", "Brazil", "Bulgaria", "Colombia", "Costa Rica", "Dominica", "Dominican Republic", "Equatorial Guinea", "Fiji", "Gabon", "Georgia", "Grenada", "Guatemala", "Guyana", "Iraq", "Jamaica", "Jordan", "Kazakhstan", "Malaysia", "Maldives", "Mauritius", "Mexico", "Namibia", "North Macedonia", "Paraguay", "Peru", "Romania", "Samoa", "Serbia", "Sri Lanka", "South Africa", "St. Lucia", "St. Vincent and the Grenadines", "Suriname", "Thailand", "Tonga", "Turkey", "Venezuela, RB"), "Upper-Middle-Income Economies",
                        ifelse(country %in% c("Antigua and Barbuda", "Australia", "Bahamas", "Barbados", "Brunei Darussalam", "Canada", "Chile", "Croatia", "Czech Republic", "Denmark", "Euro Area", "Hong Kong", "Hungary", "Iceland", "Israel", "Japan", "Korea, Rep.", "Kuwait", "Macao", "New Zealand", "Norway", "Oman", "Panama", "Poland", "Qatar", "Seychelles", "Singapore", "St. Kitts and Nevis", "Sweden", "Switzerland", "Trinidad and Tobago", "United Arab Emirates", "United Kingdom", "United States", "Uruguay"), "High-Income Economies", "NA"))))) %>%
arrange(country, year) %>%
filter(cic != "NA")

write.csv(final_regression_1_data, "final_regression_1_data.csv")

final_regression_1_data_updated <- final_regression_1_data %>%
group_by(country) %>%
count() %>%
filter(n<17) 



```

```{r follow-up data set creation}

#oecd

final_data_oecd <- read_csv("raw-data/final_regression_1_data.csv") %>%
  filter(country %in% c("Australia", "Austria", "Belgium", "Canada", "Chile", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Israel", "Italy", "Japan", "Korea", "Latvia", "Lithuania", "Luxembourg", "Mexico", "Netherlands", "New Zealand", "Norway", "Poland", "Portugal", "Slovak Republic", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey", "United Kingdom", "United States")) 

write.csv(final_data_oecd, "final_data_oecd.csv")

#level of development

final_data_high_income <- read_csv("raw-data/final_regression_1_data.csv") %>%
filter(development == "High-Income Economies")

write.csv(final_data_high_income, "final_data_high_income.csv")

final_data_upper_middle_income <- read_csv("raw-data/final_regression_1_data.csv") %>%
filter(development == "Upper-Middle-Income Economies")

write.csv(final_data_upper_middle_income, "final_data_upper_middle_income.csv")

final_data_lower_middle_income <- read_csv("raw-data/final_regression_1_data.csv") %>%
filter(development == "Lower-Middle-Income Economies")

write.csv(final_data_lower_middle_income, "final_data_lower_middle_income.csv")

final_data_low_income <- read_csv("raw-data/final_regression_1_data.csv") %>%
filter(development == "Low-Income Economies")

write.csv(final_data_low_income, "final_data_low_income.csv")

edited_data_lower_middle_income <- final_data_lower_middle_income %>%
filter(country %in% c("Angola", "Bangladesh", "Bolivia", "Ghana", "Kenya", "Moldova", "Mongolia", "Philippines", "Zambia")) %>%
group_by(year) %>%
summarize(avg_tax_gdp = mean(tax_gdp, na.rm = TRUE)) %>%
filter(year != "2018")

ggplot(edited_data_lower_middle_income_2, aes(x=year, y=avg_cd)) + geom_point() + geom_line()

edited_data_lower_middle_income_2 <- final_data_lower_middle_income %>%
filter(country %in% c("Angola", "Bangladesh", "Bolivia", "Ghana", "Kenya", "Moldova", "Mongolia", "Philippines", "Zambia")) %>%
group_by(year) %>%
summarize(avg_cd = mean(cd, na.rm = TRUE)) %>%
filter(year != "2018")

```

```{r Addition of new data sets}

#debt to gdp ratio

debt_gdp <- read_xls("raw-data/debt_gdp.xls") %>%
gather(year, value, -c(country)) %>%
rename(debt_gdp = value) %>%
mutate(debt_gdp = as.numeric(debt_gdp)) %>%
mutate(year = as.numeric(year)) %>%
mutate(debt_gdp = round(debt_gdp, digits = 2)) %>%
filter(debt_gdp != "no data") %>%
arrange(country, year)

#old popualtion

old_population <- read_csv("raw-data/old_population.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(old_pop_percent = value)

#gdp per capita

gdp_per_capita <- read_csv("raw-data/gdp_per_capita.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(gdp_per_capita = value)

gdp_per_capita_ea <- gdp_per_capita %>%
  mutate(euro_area = ifelse(country %in% c("Germany", "Spain", "France", "Italy", "Netherlands", "Austria", "Belgium", "Cyprus", "Estonia", "Finland", "Greece", "Ireland", "Latvia", "Lithuania", "Luxembourg", "Malta", "Portugal", "Slovakia", "Slovenia"), 1, 0)) %>%
  filter(euro_area == 1) %>%
  group_by(year) %>%
  summarize(gdp_per_capita = mean(gdp_per_capita)) %>%
  mutate(country = "Euro Area") %>%
  mutate(country_code = "EMU")
  
gdp_per_capita_final <- gdp_per_capita_ea %>%
  full_join(gdp_per_capita, by = c("country", "country_code", "year", "gdp_per_capita"))

#inflation 

inflation_rate <- read_csv("raw-data/inflation_rate.csv", skip = 4) %>% select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(inflation_rate = value) %>%
arrange(inflation_rate)

final_final_data_regression_1 <- read_csv("raw-data/final_regression_1_data_2_17.csv") %>%
full_join(debt_gdp, by = c("country", "year")) %>%
full_join(old_population, by = c("country", "country_code", "year")) %>%
full_join(gdp_per_capita_final, by = c("country", "country_code", "year")) %>% arrange(country, year) %>%
filter(cic != "NA") %>%
select(country, country_code, year, cic, gdp, cd, deposit_interest_rate, treasury_bill_rate, gdp_per_capita, tax_gdp, crime, eci, uncertainty, debt_gdp, old_pop_percent, business_freedom, urban_pop_growth, urbanization, monetary_freedom, property_rights, shadow_economy, investment_freedom, financial_freedom, trade_freedom, government_integrity, judicial_effectiveness, overall_score, tax_burden, government_spending, fiscal_health, labor_freedom, region, development) %>%
left_join(inflation_rate, by = c("country", "country_code", "year")) %>%
left_join(gdp_per_capita_ppp, by = c("country", "country_code", "year"))

write_csv(final_final_data_regression_1, "final_final_regression_1_data.csv")

updated_uncertainty_data <- final_regression_1_data %>%
full_join(debt_gdp, by = c("country", "year")) %>%
full_join(old_population, by = c("country", "country_code", "year")) %>%
full_join(gdp_per_capita_final, by = c("country", "country_code", "year")) %>% arrange(country, year) %>%
filter(cic != "NA") %>%
select(country, country_code, year, cic, gdp, cd, deposit_interest_rate, treasury_bill_rate, gdp_per_capita, tax_gdp, crime, eci, uncertainty, debt_gdp, old_pop_percent, business_freedom, urban_pop_growth, urbanization, monetary_freedom, property_rights, shadow_economy, investment_freedom, financial_freedom, trade_freedom, government_integrity, judicial_effectiveness, overall_score, tax_burden, government_spending, fiscal_health, labor_freedom, region, development) %>%
left_join(gdp_per_capita_ppp, by = c("country", "country_code", "year"))
  
write_csv(updated_uncertainty_data, "updated_uncertainty_data.csv")

testing <- final_final_data_regression_1 %>%
filter(development %in% c("High-Income Economies", "Upper-Middle-Income Economies")) %>%
arrange(desc(gdp_per_capita)) 

gdp_per_capita_ppp <- read_csv("raw-data/gdp_per_capita_ppp.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(gdp_per_capita_ppp = value)

business_freedom_graph <- final_final_data_regression_1 %>%
filter(!country %in% c("Zimbabwe", "Liberia", "Angola", "Botswana", "Belarus", "Namibia", "Panama", "Qatar", "Eswatini", "Congo DR", "Zambia", "Jordan", "Turkey", "Azerbaijan", "Nigeria", "Kuwait", "Venezuela, RB", "Guinea-Bissau", "Kazakhstan")) %>%
group_by(development, year) %>%
summarize(avg_business_freedom = mean(business_freedom, na.rm = TRUE)) %>%
filter(year != "2018")

ggplot(business_freedom_graph, aes(x=year, y=avg_business_freedom, color = development)) + geom_line()

urbanization_graph <- final_final_data_regression_1 %>%
filter(!country %in% c("Zimbabwe", "Liberia", "Angola", "Botswana", "Belarus", "Namibia", "Panama", "Qatar", "Eswatini", "Congo DR", "Zambia", "Jordan", "Turkey", "Azerbaijan", "Nigeria", "Kuwait", "Venezuela, RB", "Guinea-Bissau", "Kazakhstan")) %>%
group_by(development, year) %>%
summarize(avg_urbanization = mean(urbanization, na.rm = TRUE))
filter(development == "High-Income Economies") %>%
group_by(region, year)%>%
summarize(avg_urbanization = mean(urbanization, na.rm = TRUE))

ggplot(urbanization_graph, aes(x=year, y=avg_urbanization, color = development)) + geom_line()

tax_gdp_graph <- final_final_data_regression_1 %>%
filter(!country %in% c("Zimbabwe", "Liberia", "Angola", "Botswana", "Belarus", "Namibia", "Panama", "Qatar", "Eswatini", "Congo DR", "Zambia", "Jordan", "Turkey", "Azerbaijan", "Nigeria", "Kuwait", "Venezuela, RB", "Guinea-Bissau", "Kazakhstan")) %>%
group_by(development, year) %>%
summarize(avg_tax_gdp = mean(tax_gdp, na.rm = TRUE)) %>%
filter(year != "2018")

ggplot(tax_gdp_graph, aes(x=year, y=avg_tax_gdp, color = development)) + geom_line()

old_pop_graph <- final_final_data_regression_1 %>%
filter(!country %in% c("Zimbabwe", "Liberia", "Angola", "Botswana", "Belarus", "Namibia", "Panama", "Qatar", "Eswatini", "Congo DR", "Zambia", "Jordan", "Turkey", "Azerbaijan", "Nigeria", "Kuwait", "Venezuela, RB", "Guinea-Bissau", "Kazakhstan")) %>%
group_by(development, year) %>%
summarize(avg_old_pop = mean(old_pop_percent, na.rm = TRUE)) %>%
filter(year != "2018")

ggplot(old_pop_graph, aes(x=year, y=avg_old_pop, color = development)) + geom_line()

gdp_per_capita_ppp <- read_csv("raw-data/gdp_per_capita_ppp.csv", skip = 4) %>%
select(-`Indicator Name`, -`Indicator Code`) %>%
gather(year, value, -c(`Country Name`, `Country Code`)) %>%
filter(value != "NA") %>%
rename(country = `Country Name`) %>%
rename(country_code = `Country Code`) %>%
mutate(year = as.numeric(year)) %>%
rename(gdp_per_capita_ppp = value) 

gdp_per_capita_graph <- final_final_data_regression_1 %>%
filter(!country %in% c("Zimbabwe", "Liberia", "Angola", "Botswana", "Belarus", "Namibia", "Panama", "Qatar", "Eswatini", "Congo DR", "Zambia", "Jordan", "Turkey", "Azerbaijan", "Nigeria", "Kuwait", "Venezuela, RB", "Guinea-Bissau", "Kazakhstan")) %>%
group_by(development, year) %>%
summarize(avg_gdp_per_capita = mean(gdp_per_capita_ppp, na.rm = TRUE)) 

ggplot(gdp_per_capita_graph, aes(x=year, y=avg_gdp_per_capita, color = development)) + geom_line()

monetary_graph <- final_final_data_regression_1 %>%
filter(!country %in% c("Zimbabwe", "Liberia", "Angola", "Botswana", "Belarus", "Namibia", "Panama", "Qatar", "Eswatini", "Congo DR", "Zambia", "Jordan", "Turkey", "Azerbaijan", "Nigeria", "Kuwait", "Venezuela, RB", "Guinea-Bissau", "Kazakhstan")) %>%
group_by(development, year) %>%
summarize(avg_monetary_freedom = mean(monetary_freedom, na.rm = TRUE)) 

ggplot(monetary_graph, aes(x=year, y=avg_monetary_freedom, color = development)) + geom_line()

urban_pop_growth_graph <- final_final_data_regression_1 %>%
filter(!country %in% c("Zimbabwe", "Liberia", "Angola", "Botswana", "Belarus", "Namibia", "Panama", "Qatar", "Eswatini", "Congo DR", "Zambia", "Jordan", "Turkey", "Azerbaijan", "Nigeria", "Kuwait", "Venezuela, RB", "Guinea-Bissau", "Kazakhstan")) %>%
group_by(development, year) %>%
summarize(avg_urb_pop_growth = mean(urban_pop_growth, na.rm = TRUE)) 

ggplot(urban_pop_growth_graph, aes(x=year, y=avg_urb_pop_growth, color = development)) + geom_line()

  
```
